version: '3'
services:
  splash-1:
    image: scrapinghub/splash
    container_name: splash-1
    ports: ["8051:8050"]
    restart: unless-stopped
    command: ["--max-timeout", "60"]

  splash-2:
    image: scrapinghub/splash
    container_name: splash-2
    ports: ["8052:8050"]
    restart: unless-stopped
    command: ["--max-timeout", "60"]

  splash-3:
    image: scrapinghub/splash
    container_name: splash-3
    ports: ["8053:8050"]
    restart: unless-stopped
    command: ["--max-timeout", "60"]

  haproxy:
    image: haproxy:lts-alpine
    container_name: splash-lb
    ports: ["9000:9000"]
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - splash-1
      - splash-2
      - splash-3
